# Automatically update versions for pip

version: 2
updates:

  # Maintain dependencies for Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "00:00"

  # Maintain dependencies for Github Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "00:00"
    groups:
      github:
        patterns:
          - "actions/*"
